"""update user model

Revision ID: 994f52a03277
Revises: d745fba5620d
Create Date: 2025-10-14 12:44:50.200005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994f52a03277'
down_revision: Union[str, None] = 'd745fba5620d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('ordered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'ordered')
    # ### end Alembic commands ###
